spring:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect    #방언 떄문에 문제가 생김
        query.in_clause_parameter_padding: true